# Generated by Django 5.0 on 2023-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=50, verbose_name='Title 1')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('title2', models.CharField(blank=True, max_length=50, verbose_name='Title 2')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('title3', models.CharField(blank=True, max_length=50, verbose_name='Title 3')),
                ('text3', models.TextField(verbose_name='Text 3')),
                ('title4', models.CharField(blank=True, max_length=50, verbose_name='Title 4')),
                ('text4', models.TextField(verbose_name='Text 4')),
                ('title5', models.CharField(blank=True, max_length=50, verbose_name='Title 5')),
                ('text5', models.TextField(verbose_name='Text 5')),
                ('title6', models.CharField(blank=True, max_length=50, verbose_name='Title 6')),
                ('text6', models.TextField(verbose_name='Text 6')),
                ('title7', models.CharField(blank=True, max_length=50, verbose_name='Title 7')),
                ('text7', models.TextField(verbose_name='Text 7')),
            ],
        ),
    ]
