# Generated by Django 5.0 on 2023-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_title_text1_alter_title_text2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='background',
            field=models.ImageField(default=1, upload_to='', verbose_name='Background'),
            preserve_default=False,
        ),
    ]
