# Generated by Django 5.0 on 2023-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40, verbose_name='Title')),
                ('time', models.CharField(max_length=25, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Open Days',
                'verbose_name_plural': 'Open Days',
            },
        ),
        migrations.CreateModel(
            name='ReservationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Reservation Content',
                'verbose_name_plural': 'Reservation Content',
            },
        ),
    ]
