# Generated by Django 5.0 on 2023-12-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_opendays_reservationcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('surname', models.CharField(max_length=60, verbose_name='Surname')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('date', models.CharField(max_length=10, verbose_name='Date')),
                ('time', models.CharField(max_length=5, verbose_name='Time')),
            ],
        ),
    ]
