# Generated by Django 5.0 on 2023-12-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_reservation_date_alter_reservation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='res_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='email',
            new_name='res_email',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='surname',
            new_name='res_lastname',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='username',
            new_name='res_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone',
            new_name='res_phone',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='res_time',
        ),
    ]
