# Generated by Django 5.0 on 2023-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_date_reservation_res_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='res_date',
            field=models.CharField(max_length=10, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_time',
            field=models.CharField(max_length=5, verbose_name='Time'),
        ),
    ]
