# Generated by Django 5.0 on 2023-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_reservation_res_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('info', models.CharField(max_length=80, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Contact Content',
                'verbose_name_plural': 'Contact Content',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social1', models.URLField(verbose_name='Social 1')),
                ('social2', models.URLField(verbose_name='Social 2')),
                ('social3', models.URLField(verbose_name='Social 3')),
                ('social4', models.URLField(verbose_name='Social 4')),
                ('google_map', models.TextField(verbose_name='Google Map')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
