# Generated by Django 5.0 on 2023-12-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Info')),
                ('price', models.FloatField(verbose_name='Price')),
                ('special', models.BooleanField(blank=True, verbose_name='Special yes/no')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
            ],
        ),
    ]
